  /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Controller.CoursesBAL;
import Controller.TeachersBAL;
import Controller.teacherCourseBAL;
import static Controller.teacherCourseBAL.c_list;
import Model.CourseBean;
import Model.IdBean;
import Model.TeachersBean;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vijay kumar
 */
public class assignCourse extends javax.swing.JInternalFrame {

    /**
     * Creates new form assignCourse
     */
      ArrayList<TeachersBean> teacher_list;
      ArrayList<CourseBean> course_list;
      DefaultTableModel model;
     
      IdBean bean;
      DefaultListModel teacher_model;
      DefaultComboBoxModel model_c;
    public assignCourse() {
        initComponents();
       teacher_list=new  ArrayList<TeachersBean>();
     course_list=new   ArrayList<CourseBean>();
           teacher_list=TeachersBAL.getTeacherIncombo();
       
        course_list=CoursesBAL.getCourse();
        this.jList1.setModel(new DefaultListModel());
        teacher_model=(DefaultListModel) this.jList1.getModel();
        
 
 
        
        
       
        this.jComboBox_course.setVisible(true);
     
        
        
        
              c_list = new ArrayList<HashMap<String , Object>>();
              model=     model = (DefaultTableModel) this.jTable_teacherCourse.getModel();
            
       






      showinBox_course();
            showIntable();
            
            ShowInTeacherList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_teacherCourse = new javax.swing.JTable();
        jComboBox_course = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Assign Courses");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_teacherCourse.setBackground(new java.awt.Color(0, 0, 0));
        jTable_teacherCourse.setForeground(new java.awt.Color(255, 255, 255));
        jTable_teacherCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Teacher ID", "Teacher Name", "Course"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_teacherCourse);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 140, 370, 390));

        jComboBox_course.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(jComboBox_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 250, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Teacher Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 140, 19));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Course:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 160, 20));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Assign");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 130, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        jLabel3.setText("Back");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, 40));

        jList1.setBackground(new java.awt.Color(0, 0, 0));
        jList1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 130, 220));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("ASSIGN COURSE TO TEACHERS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stuFees.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 
int Id=this.jComboBox_course.getSelectedIndex();
       int iD= this.jList1.getSelectedIndex();
        int teacherID= teacher_list.get(iD).getTeacher_id();
        int course_id=course_list.get(Id).getCourse_id();
            ( (DefaultListModel)this.jList1.getModel()).clear();
            System.out.println("terer"+teacherID);
            teacherCourseBAL.addTeacher_course(teacherID, course_id);
            TeachersBAL.updateTeacherStatus(teacherID);
            
            
            teacher_list = Controller.TeachersBAL.getTeacherIncombo();
         for (TeachersBean tb : teacher_list) {
          this.teacher_model.addElement(tb); 
    }
            
        showIntable();
                
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Adminform().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked
public void showIntable() {
        model.setRowCount(0);
       // System.out.println("---"+StudentBAL.getStuSubj());
             c_list = teacherCourseBAL.getTeacherCourse();
        for (HashMap<String ,Object> map: c_list) {
            Vector v=new Vector();
            v.add(map.get("id"));
            v.add(map.get("teacher_name"));
            v.add(map.get("course"));
          
             v.add(v);
            model.addRow(v);

        }

    }
     public void showinBox_teacher() {
      //  list = TeachersBAL.getTeacher();
        for (TeachersBean Bean : teacher_list) {
            //this.jComboBox_teachersname.addItem(""+Bean);
this.teacher_model.addElement(Bean);
        }
        
     
    }
      
          public void showinBox_course() {
   course_list=CoursesBAL.getCourse();
        for (CourseBean Bean : course_list) {
          this.jComboBox_course.addItem(""+Bean);
//this.model_c.addElement(Bean);
        }
        
     
    }
          
      
          
           public void ShowInTeacherList(){
    
     for (TeachersBean tb : teacher_list) {
          this.teacher_model.addElement(tb); 
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox_course;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_teacherCourse;
    // End of variables declaration//GEN-END:variables
}
