/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CoursesBAL;
import Controller.TeachersBAL;
import Model.CourseBean;
import Model.TeachersBean;
import static View.TeacherInternalform.list;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vijay kumar
 */

public class Course extends javax.swing.JInternalFrame {

    /**
     * Creates new form Course
     */
    DefaultTableModel model1;
        public static ArrayList<CourseBean> course_list;
        int time=0;
    public Course() {
        
    //    
        initComponents();
        model1 = (DefaultTableModel) this.jTable1.getModel();
        course_list = new ArrayList<CourseBean>();
        Showintable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_remove = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jButton_add = new javax.swing.JButton();
        jTextField_course = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Courses");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin_.jpg"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Courses");
        jDesktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jDesktopPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 102, 360, 470));

        jButton_remove.setBackground(new java.awt.Color(0, 0, 0));
        jButton_remove.setForeground(new java.awt.Color(255, 255, 255));
        jButton_remove.setText("Remove");
        jButton_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_removeActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 369, 105, -1));

        jButton_update.setBackground(new java.awt.Color(0, 0, 0));
        jButton_update.setForeground(new java.awt.Color(255, 255, 255));
        jButton_update.setText("Update");
        jButton_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_updateMouseClicked(evt);
            }
        });
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 407, 95, -1));

        jButton_add.setBackground(new java.awt.Color(0, 0, 0));
        jButton_add.setForeground(new java.awt.Color(255, 255, 255));
        jButton_add.setText("Add Courses");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 369, -1, -1));

        jTextField_course.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_courseActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jTextField_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 182, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        jLabel3.setText("Back");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jDesktopPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, 50));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Add Courses");
        jDesktopPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stuFees.jpg"))); // NOI18N
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 840, 590));

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        // TODO add your handling code here:
          int id = this.jTable1.getSelectedRow(); 
        String course = this.jTextField_course.getText();
    
        model1.setValueAt(this.jTextField_course.getText(), id, 1);
  
       

        int z = id + 1;
        int i = CoursesBAL.updateCourse(id+1, course);
        JOptionPane.showMessageDialog(this, z + "'s no: id  is Updated ");
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jTextField_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_courseActionPerformed

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        // TODO add your handling code here:
             String name = this.jTextField_course.getText();
        
       
        
        
        int id = CoursesBAL.addCourse(name);

        JOptionPane.showMessageDialog(this, name + " is added as new course ");

        Showintable();
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jButton_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_removeActionPerformed
     int Id = course_list.get(this.jTable1.getSelectedRow()).getCourse_id();
        int row = CoursesBAL.cascadeDelCourse(Id);
        JOptionPane.showMessageDialog(null, row + " deleted");
        this.jTextField_course.setText("");
       
        
        Showintable();        
    }//GEN-LAST:event_jButton_removeActionPerformed

    private void jButton_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_updateMouseClicked
        // TODO add your handling code here:
         
       // this.jTextField_course.setText(course_list.get(id).getCourse());
    }//GEN-LAST:event_jButton_updateMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         int id = this.jTable1.getSelectedRow();
this.jTextField_course.setText(course_list.get(id+1).getCourse());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Adminform().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

public void Showintable() {
        model1.setRowCount(0);
                course_list = CoursesBAL.getCourse();
        for (CourseBean Bean : course_list) {
        Vector v=new Vector();
            v.add(Bean.getCourse_id());
              v.add(Bean.getCourse());
              

            model1.addRow(v);

        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_remove;
    private javax.swing.JButton jButton_update;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_course;
    // End of variables declaration//GEN-END:variables
}
