/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.StudentBAL;
import Controller.StudentFeesBAL;
import Model.IdBean;
import Model.StudentBean;
import Model.StudentSearchingBean;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vijay kumar
 */
public class FeesInternalframe extends javax.swing.JInternalFrame {

    /**
     * Creates new form FeesInternalframe
     */
    static int student_id;
    static int teacher_id;
    DefaultTableModel model;
    int time=0;
       ArrayList<StudentBean> fees_list;
       ArrayList<StudentSearchingBean> searchingList;
    public FeesInternalframe() {
        initComponents();
        teacher_id=Loginframe.teacher_id;
                model= model = (DefaultTableModel) this.jTable1.getModel();
                  showintable(teacher_id);
                   new Thread() {
            public void run() {
                while (time == 0) {
                               Calendar cal = new GregorianCalendar();
                    int hour = cal.get(Calendar.HOUR);
                    int min = cal.get(Calendar.MINUTE);
                    int sec = cal.get(Calendar.SECOND);
                    int am_pm = cal.get(Calendar.AM_PM);
                    
                    String day;
                    if (am_pm == 1) {
                        day = "PM";
                    } else {
                        day = "AM";
                        
                    }
                    
                    String NowTime = hour + ":" + min + ":" + sec + " " + day;
                   
                    jLabel_time.setText(NowTime);
                    
                }
                
            }
            
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox_notpaid = new javax.swing.JCheckBox();
        jCheckBox_paid = new javax.swing.JCheckBox();
        jLabel_studentname = new javax.swing.JLabel();
        jTextField_search = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton_update = new javax.swing.JButton();
        jLabel_time = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Students Fees Records");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID:", "Student Name", "Fees Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 460, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fees Status:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jCheckBox_notpaid.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jCheckBox_notpaid);
        jCheckBox_notpaid.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCheckBox_notpaid.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_notpaid.setText("Not Paid");
        jCheckBox_notpaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_notpaidActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox_notpaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        jCheckBox_paid.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jCheckBox_paid);
        jCheckBox_paid.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCheckBox_paid.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_paid.setText("Paid");
        getContentPane().add(jCheckBox_paid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jLabel_studentname.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_studentname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel_studentname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 170, 20));

        jTextField_search.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_search.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_searchKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 400, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, -1, 20));

        jButton_update.setBackground(new java.awt.Color(0, 0, 0));
        jButton_update.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_update.setForeground(new java.awt.Color(255, 255, 255));
        jButton_update.setText("Upadate Fees Status");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jLabel_time.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_time.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_time.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black));
        getContentPane().add(jLabel_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 150, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Student Fees Records");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 410, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stuFees.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 880, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_notpaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_notpaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_notpaidActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        int id = this.jTable1.getSelectedRow(); 
        
        String feesStatus="";
    if (this.jCheckBox_paid.isSelected()){
    feesStatus="Paid";
    }
    else {
    feesStatus="Not Paid";
    }
    int i=StudentFeesBAL.updateFeesStatus(student_id, feesStatus);
    model.setValueAt(feesStatus, id, 2);
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
          int id = this.jTable1.getSelectedRow();
          String name=(String) this.model.getValueAt(id, 1);
          IdBean stu_id=StudentFeesBAL.getRoll(teacher_id, name);
       student_id=Integer.parseInt(""+stu_id);
       this.jLabel_studentname.setText(name);
       
                 
          
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchKeyReleased
       String search=this.jTextField_search.getText();
        Showintable(search,teacher_id);
    }//GEN-LAST:event_jTextField_searchKeyReleased

      public void showintable(int teacher_id) {
        model.setRowCount(0);
        

        fees_list= StudentFeesBAL.getStudents_fees(teacher_id);
         for (StudentBean studentBean : fees_list) {
             Vector V = new Vector();
             V.add(studentBean.getStudent_id());
             V.add(studentBean.getStudent_name());
             V.add(studentBean.getFees_status());
      model.addRow(V);
         }
     }
       public void Showintable(String search,int teacherId) {
        model.setRowCount(0);
                searchingList = StudentBAL.SearchStudent(search,teacherId);
        for (StudentSearchingBean Bean :searchingList ) {
        Vector v=new Vector();
              v.add(Bean.getStu_id());
                  
              v.add(Bean.getStu_name());
              v.add(Bean.getFeesStatus());
             

            model.addRow(v);

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_update;
    private javax.swing.JCheckBox jCheckBox_notpaid;
    private javax.swing.JCheckBox jCheckBox_paid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_studentname;
    private javax.swing.JLabel jLabel_time;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_search;
    // End of variables declaration//GEN-END:variables
}
