/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.StudentBAL;
import Controller.StudentFeesBAL;
import Controller.TeachersBAL;
import Model.StudentBean;
import Model.TeacherIDBean;
import Model.TeachersBean;
import static View.TeacherInternalform.list;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vijay kumar
 */
public class StudentListInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form StudentListInternalFrame
     */
     DefaultComboBoxModel comboboxmodel;
     DefaultTableModel model;
     ArrayList<StudentBean> stu_list;
   
     TeacherIDBean Bean;
     int time=0;
    public StudentListInternalFrame() {
        initComponents();
            comboboxmodel= (DefaultComboBoxModel) this.jComboBox1.getModel();
         jComboBox1.setVisible(true);
         model=(DefaultTableModel) this.jTable1.getModel();
         new Thread() {
            public void run() {
                while (time == 0) {
                               Calendar cal = new GregorianCalendar();
                    int hour = cal.get(Calendar.HOUR);
                    int min = cal.get(Calendar.MINUTE);
                    int sec = cal.get(Calendar.SECOND);
                    int am_pm = cal.get(Calendar.AM_PM);
                    
                    String day;
                    if (am_pm == 1) {
                        day = "PM";
                    } else {
                        day = "AM";
                        
                    }
                    
                    String NowTime = hour + ":" + min + ":" + sec + " " + day;
                   
                    jLabel_time.setText(NowTime);
                    
                }
                
            }
            
        }.start();
         showinBox_teacher();
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel_time = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Students List");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tearcher Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID:", "Student Name:", "Course"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 114, 750, 410));

        jComboBox1.setBackground(new java.awt.Color(0, 0, 102));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 590, -1));

        jLabel_time.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_time.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_time.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.black, java.awt.Color.darkGray));
        getContentPane().add(jLabel_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Student List");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stuFees.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 520));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stuFees.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
int id=this.jComboBox1.getSelectedIndex();
        this.jComboBox1.getSelectedIndex();
        showintable(id+1);
    }//GEN-LAST:event_jComboBox1ItemStateChanged

 public void showinBox_teacher() {
        list = TeachersBAL.getTeacher();
        for (TeachersBean Bean : list) {
           
            this.jComboBox1.addItem(""+Bean);

        }
     
    }
  public void showintable(int teacher_id) {
        model.setRowCount(0);
        

        stu_list= StudentBAL.getStudent(teacher_id);
         for (StudentBean studentBean : stu_list) {
             Vector V = new Vector();
             V.add(studentBean.getStudent_id());
             V.add(studentBean.getStudent_name());
         
             V.add(studentBean.getCourse());
      model.addRow(V);
         }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_time;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
