/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LoginBAL;
import Controller.StudentBAL;
import Controller.StudentFeesBAL;
import Controller.TeachersBAL;
import Model.IdBean;
import Model.StudentBean;
import Model.Subjectbean;
import Model.TeachersBean;
import Model.course_idBean;


import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vijay kumar
 */
public class Teacher extends javax.swing.JFrame {

    /**
     * Creates new form Teacher
     */
      DefaultTableModel model;
        ArrayList<StudentBean> stu_list;
        ArrayList<TeachersBean> list;
public static int teacher_id;
       public static int  course_id;
       public static int stu_id;
       FeesInternalframe fees_frame=null;
    public Teacher() {
        initComponents();
    }
           public Teacher(String name) {
          
        
        initComponents();
        
               System.out.println("stuid"+stu_id);
        fees_frame=new FeesInternalframe();
        list = TeachersBAL.getTeacher();
        model= model = (DefaultTableModel) this.jTable1.getModel();
       teacher_id=Loginframe.teacher_id;
  
      
               System.out.println("tttttt"+teacher_id);
        showintable(teacher_id);
   

course_idBean Idbean=LoginBAL.getCourseId(teacher_id);
        
       String i=""+Idbean;
        course_id=Integer.parseInt(""+i);
       
        this.jLabel_title.setText(name);
       
               fees_frame=new FeesInternalframe();
         Subjectbean subBean=LoginBAL.getCourse(course_id);
          this.jLabel_subj.setText(""+subBean);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel_subj = new javax.swing.JLabel();
        jLabel_title = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField_stuname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_roll = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_fees = new javax.swing.JTextField();
        jButton_add = new javax.swing.JButton();
        jButton_upadate = new javax.swing.JButton();
        jButton_remove = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management System");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID:", "Student Name", "Roll No:", "Fees", "Course"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jDesktopPane2.add(jScrollPane1);
        jScrollPane1.setBounds(720, 80, 480, 570);

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Subject of Specilization:");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.red));
        jDesktopPane2.add(jLabel3);
        jLabel3.setBounds(750, 50, 228, 25);

        jLabel_subj.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_subj.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_subj.setText("jLabel7");
        jDesktopPane2.add(jLabel_subj);
        jLabel_subj.setBounds(990, 50, 240, 24);

        jLabel_title.setFont(new java.awt.Font("One Stroke Script LET", 1, 48)); // NOI18N
        jLabel_title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_title.setText(" ");
        jDesktopPane2.add(jLabel_title);
        jLabel_title.setBounds(400, 80, 210, 70);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View Students Records");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButton1);
        jButton1.setBounds(30, 330, 631, 33);

        jTextField_stuname.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField_stuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_stunameActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jTextField_stuname);
        jTextField_stuname.setBounds(340, 400, 236, 25);

        jLabel4.setBackground(new java.awt.Color(204, 102, 0));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student Name:");
        jDesktopPane2.add(jLabel4);
        jLabel4.setBounds(210, 410, 102, 19);

        jTextField_roll.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField_roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_rollActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jTextField_roll);
        jTextField_roll.setBounds(340, 450, 236, 25);

        jLabel5.setBackground(new java.awt.Color(204, 153, 0));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Roll no:");
        jDesktopPane2.add(jLabel5);
        jLabel5.setBounds(250, 460, 53, 19);

        jLabel6.setBackground(new java.awt.Color(255, 153, 0));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fees:");
        jDesktopPane2.add(jLabel6);
        jLabel6.setBounds(270, 500, 39, 19);

        jTextField_fees.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField_fees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_feesActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jTextField_fees);
        jTextField_fees.setBounds(340, 500, 236, 25);

        jButton_add.setBackground(new java.awt.Color(0, 0, 0));
        jButton_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton_add.setForeground(new java.awt.Color(255, 255, 255));
        jButton_add.setText("Add");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButton_add);
        jButton_add.setBounds(40, 570, 205, 27);

        jButton_upadate.setBackground(new java.awt.Color(0, 0, 0));
        jButton_upadate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton_upadate.setForeground(new java.awt.Color(255, 255, 255));
        jButton_upadate.setText("Update");
        jButton_upadate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_upadateActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButton_upadate);
        jButton_upadate.setBounds(250, 570, 174, 27);

        jButton_remove.setBackground(new java.awt.Color(0, 0, 0));
        jButton_remove.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton_remove.setForeground(new java.awt.Color(255, 255, 255));
        jButton_remove.setText("Delete");
        jButton_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_removeActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButton_remove);
        jButton_remove.setBounds(430, 570, 192, 27);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButton2);
        jButton2.setBounds(1100, 10, 77, 23);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("WELCOME");
        jDesktopPane2.add(jLabel2);
        jLabel2.setBounds(110, 30, 190, 43);
        jLabel2.getAccessibleContext().setAccessibleName("WELCOME");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("WELCOME");
        jDesktopPane2.add(jLabel7);
        jLabel7.setBounds(110, 30, 190, 43);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Students Records");
        jDesktopPane2.add(jLabel1);
        jLabel1.setBounds(190, 270, 310, 43);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Untitled-1 copy.jpg"))); // NOI18N
        jDesktopPane2.add(jLabel8);
        jLabel8.setBounds(0, 0, 1200, 650);

        getContentPane().add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Loginframe().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_removeActionPerformed
        // TODO add your handling code here:

        int i =StudentBAL.cascadeDelStudent(stu_id);
        JOptionPane.showMessageDialog(null, stu_id + " deleted");
        this.jTextField_stuname.setText("");
        this.jTextField_roll.setText("");
        this.jTextField_fees.setText("");

        showintable(teacher_id);
    }//GEN-LAST:event_jButton_removeActionPerformed

    private void jButton_upadateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_upadateActionPerformed
        int id=this.jTable1.getSelectedRow();
        String stu_name=this.jTextField_stuname.getText();
        String roll_no=this.jTextField_roll.getText();
        double fees=Double.parseDouble(this.jTextField_fees.getText());

        model.setValueAt(stu_name, id, 1);
        model.setValueAt(roll_no, id, 2);
        model.setValueAt(fees, id, 3);

        int i=StudentBAL.updateStudent(stu_id, stu_name, roll_no, fees);

        JOptionPane.showMessageDialog(this, stu_id+ "'s no: Student id  is Updated ");

        showintable(teacher_id);
        this.jTextField_stuname.setText("");
        this.jTextField_roll.setText("");
        this.jTextField_fees.setText("");
    }//GEN-LAST:event_jButton_upadateActionPerformed

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed

        Subjectbean subBean=LoginBAL.getCourse(course_id);
        String course=""+subBean;
        String stu_name=this.jTextField_stuname.getText();
        String roll_no=this.jTextField_roll.getText();
        double fees=Double.parseDouble(this.jTextField_fees.getText());

        int iD =StudentBAL.addStudent(stu_name, roll_no,fees,course,teacher_id  );

        //Model.setRowCount(0);
        JOptionPane.showMessageDialog(this, stu_name+" is inserted as a new Srudent");
        showintable(teacher_id);
        this.jTextField_stuname.setText("");
        this.jTextField_roll.setText("");
        this.jTextField_fees.setText("");
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jTextField_feesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_feesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_feesActionPerformed

    private void jTextField_rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_rollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_rollActionPerformed

    private void jTextField_stunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_stunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_stunameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(fees_frame!=null){
            this.jDesktopPane2.add(fees_frame);

            fees_frame.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int id = this.jTable1.getSelectedRow();
        String studentName=(String) this.model.getValueAt(id, 1);
        String roll_no=(String) this.model.getValueAt(id, 2);
        double fees=(double) this.model.getValueAt(id, 3);
        this.jTextField_stuname.setText(studentName);
        this.jTextField_roll.setText(roll_no);
        this.jTextField_fees.setText(""+fees);
        IdBean student_id=StudentFeesBAL.getRoll(teacher_id,studentName);
        stu_id=Integer.parseInt(""+student_id);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Teacher().setVisible(true);
//            }
//        });
//    }
    public void showintable(int teacher_id) {
        model.setRowCount(0);
        

        stu_list= StudentBAL.getStudent(teacher_id);
         for (StudentBean studentBean : stu_list) {
             Vector V = new Vector();
             V.add(studentBean.getStudent_id());
             V.add(studentBean.getStudent_name());
             V.add(studentBean.getRoll_no());
             V.add(studentBean.getFees());
             V.add(studentBean.getCourse());
      model.addRow(V);
         }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_remove;
    private javax.swing.JButton jButton_upadate;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_subj;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_fees;
    private javax.swing.JTextField jTextField_roll;
    private javax.swing.JTextField jTextField_stuname;
    // End of variables declaration//GEN-END:variables
}
