/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LoginBAL;
import Controller.TeachersBAL;

import Model.TeachersBean;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vijay kumar
 */
public class TeacherInternalform extends javax.swing.JInternalFrame {

    /**
     * Creates new form TeacherInternalform
     */
    DefaultTableModel model;
        public static ArrayList<TeachersBean> list;
        
    public TeacherInternalform() {
        initComponents();
        model = (DefaultTableModel) this.jTable1.getModel();
        list = new ArrayList<TeachersBean>();
        showintable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        jRadioButton_female = new javax.swing.JRadioButton();
        jRadioButton_male = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField_age = new javax.swing.JTextField();
        jButton_update = new javax.swing.JButton();
        jButton_add = new javax.swing.JButton();
        jButton_remove = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton_update1 = new javax.swing.JButton();
        jButton_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, java.awt.Color.red, java.awt.Color.black));
        setClosable(true);
        setFrameIcon(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Age:");
        jDesktopPane2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Teacher's Name:");
        jDesktopPane2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 20));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");
        jDesktopPane2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        jTextField_name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jDesktopPane2.add(jTextField_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 230, -1));

        jRadioButton_female.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton_female);
        jRadioButton_female.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRadioButton_female.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_female.setText("Female");
        jDesktopPane2.add(jRadioButton_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        jRadioButton_male.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton_male);
        jRadioButton_male.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRadioButton_male.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_male.setText("Male");
        jRadioButton_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_maleActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jRadioButton_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 70, -1));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Teacher's ID:", "Teacher's Name:", "Age:", "Gender:", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jDesktopPane2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 110, 440, -1));

        jTextField_age.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jDesktopPane2.add(jTextField_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 230, -1));

        jButton_update.setBackground(new java.awt.Color(0, 0, 0));
        jButton_update.setForeground(new java.awt.Color(255, 255, 255));
        jButton_update.setText("Update");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButton_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 100, -1));

        jButton_add.setBackground(new java.awt.Color(0, 0, 0));
        jButton_add.setForeground(new java.awt.Color(255, 255, 255));
        jButton_add.setText("Add ");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButton_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 100, -1));

        jButton_remove.setBackground(new java.awt.Color(0, 0, 0));
        jButton_remove.setForeground(new java.awt.Color(255, 255, 255));
        jButton_remove.setText("Remove");
        jButton_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_removeActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButton_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 100, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gender:");
        jDesktopPane2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 190, -1));

        jButton_update1.setBackground(new java.awt.Color(204, 102, 0));
        jButton_update1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_update1.setText("Update");
        jButton_update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_update1ActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButton_update1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 100, -1));

        jButton_back.setBackground(new java.awt.Color(0, 0, 0));
        jButton_back.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton_back.setForeground(new java.awt.Color(255, 255, 255));
        jButton_back.setText("Back");
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButton_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Add Teachers");
        jDesktopPane2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stuFees.jpg"))); // NOI18N
        jDesktopPane2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 860, 520));

        getContentPane().add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 850, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_maleActionPerformed

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        // TODO add your handling code here:
        String name = this.jTextField_name.getText();
        int age=Integer.parseInt(this.jTextField_age.getText());
       String password=this.jPasswordField2.getText();
        String gender = "";
        if (this.jRadioButton_male.isSelected()) {
             gender = "Male";
        } else {
         gender = "Female";
        }
        int id = TeachersBAL.addTeacher(name, gender, age,password);
        
        JOptionPane.showMessageDialog(this, name + " is added as new Teacher ");
     int i=LoginBAL.addLogin(name, password);
        showintable();
        
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jButton_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_removeActionPerformed
        // TODO add your handling code here:
            int Id = list.get(this.jTable1.getSelectedRow()).getTeacher_id();
        int row = TeachersBAL.cascadeDelTeacher(Id);
        JOptionPane.showMessageDialog(null, row + " deleted");
        this.jTextField_name.setText("");
        this.jTextField_age.setText("");
        
        showintable();

    }//GEN-LAST:event_jButton_removeActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
             int id = this.jTable1.getSelectedRow(); 
        String name = this.jTextField_name.getText();
       int age=Integer.parseInt(this.jTextField_age.getText());
       String password=this.jPasswordField2.getText();
       
        String gender= "";
        if (this.jRadioButton_male.isSelected()) {
            gender="Male";

        } else {
            gender="Female";

        }
        model.setValueAt(this.jTextField_name.getText(), id, 1);
        model.setValueAt(this.jTextField_age.getText(), id, 2);
        model.setValueAt(gender, id, 3);
        model.setValueAt(this.jPasswordField2.getText(), id, 4);
       

        int z = id + 1+1;
        int i = TeachersBAL.updateTeacher(id+1, name, gender, age,password);
        int j=LoginBAL.updateLogin(id, name, password);
        JOptionPane.showMessageDialog(this, z + "'s no: id  is Updated ");
        showintable();
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        int id = this.jTable1.getSelectedRow();

        this.jTextField_name.setText(list.get(id).getTeacher_name());
       
        this.jTextField_age.setText(""+list.get(id).getAge());

        if (list.get(id).getGender().equals("Male")) {

            this.jRadioButton_male.setSelected(true);
        } else {
            this.jRadioButton_female.setSelected(true);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jButton_update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_update1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_update1ActionPerformed

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Adminform().setVisible(true);
    }//GEN-LAST:event_jButton_backActionPerformed

public void showintable() {
        model.setRowCount(0);
                list = TeachersBAL.getTeacher();
        for (TeachersBean Bean : list) {
        Vector v=new Vector();
            v.add(Bean.getTeacher_id());
              v.add(Bean.getTeacher_name());
              v.add(Bean.getAge());
              v.add(Bean.getGender());
              v.add(Bean.getPass());

            model.addRow(v);

        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_back;
    private javax.swing.JButton jButton_remove;
    private javax.swing.JButton jButton_update;
    private javax.swing.JButton jButton_update1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButton_female;
    private javax.swing.JRadioButton jRadioButton_male;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_age;
    private javax.swing.JTextField jTextField_name;
    // End of variables declaration//GEN-END:variables
}

